spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: stripe-payments

  datasource:
    url: jdbc:postgresql://localhost:5432/stripe_playground
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

stripe:
  api:
    secret-key: ${STRIPE_SECRET_KEY}
    publishable-key: ${STRIPE_PUBLISHABLE_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}